language: node_js
node_js:
  - 0.10
before_script:
  - npm install -g gulp

before_install:  
  - sudo apt-get install libcairo2-dev
  - sudo apt-get install libjpeg-dev
  - sudo apt-get install libgif-dev
